// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBstjv3GoJZcBb4dHALoeaJvegmKK7jY',
    appId: '1:272596660522:web:47bdeb4f88d1f879c92e53',
    messagingSenderId: '272596660522',
    projectId: 'medical-diagnostic-agent',
    authDomain: 'medical-diagnostic-agent.firebaseapp.com',
    storageBucket: 'medical-diagnostic-agent.firebasestorage.app',
    measurementId: 'G-K3X8K0EF6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmp1eqTj6QcUtR_7nmkS65XjVSA09WDaI',
    appId: '1:272596660522:android:b465690008e0677ec92e53',
    messagingSenderId: '272596660522',
    projectId: 'medical-diagnostic-agent',
    storageBucket: 'medical-diagnostic-agent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Hy7aJ7-uSyyqP3pm_0oGFI-Imt_YBQA',
    appId: '1:272596660522:ios:533e7736d27cf114c92e53',
    messagingSenderId: '272596660522',
    projectId: 'medical-diagnostic-agent',
    storageBucket: 'medical-diagnostic-agent.firebasestorage.app',
    iosBundleId: 'com.example.dentalMedicineAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Hy7aJ7-uSyyqP3pm_0oGFI-Imt_YBQA',
    appId: '1:272596660522:ios:533e7736d27cf114c92e53',
    messagingSenderId: '272596660522',
    projectId: 'medical-diagnostic-agent',
    storageBucket: 'medical-diagnostic-agent.firebasestorage.app',
    iosBundleId: 'com.example.dentalMedicineAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBstjv3GoJZcBb4dHALoeaJvegmKK7jY',
    appId: '1:272596660522:web:71ce10c8fc27f651c92e53',
    messagingSenderId: '272596660522',
    projectId: 'medical-diagnostic-agent',
    authDomain: 'medical-diagnostic-agent.firebaseapp.com',
    storageBucket: 'medical-diagnostic-agent.firebasestorage.app',
    measurementId: 'G-MVW8F5JWE9',
  );
}
